/* eslint-disable prettier/prettier */
/* eslint-disable eol-last */
/* eslint-disable prettier/prettier */
/* eslint-disable prettier/prettier */
export default [
    {
        id: Date.now(),
        Nombre: 'The Willows',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Orchard House',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
    {
        id: Date.now(),
        Nombre: 'Pizza',
        image: '../img/pizza.png',
        Direccion: '',
        NumeroHabitaciones: 'Trending',
        Superficie: 'Trending',
        CostoRenta: 'Trending',
        Calificacion: 'Trending',
        Icono: 'Trending',
    },
];